-- MySQL Script generated by MySQL Workbench
-- Thu May 30 09:57:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pwl2032
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pwl2032
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pwl2032` DEFAULT CHARACTER SET utf8 ;
USE `pwl2032` ;

-- -----------------------------------------------------
-- Table `pwl2032`.`kartu_keluarga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwl2032`.`kartu_keluarga` (
  `id` VARCHAR(15) NOT NULL,
  `kepala_keluarga` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwl2032`.`penduduk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwl2032`.`penduduk` (
  `nik` VARCHAR(16) NOT NULL,
  `nama` VARCHAR(100) NOT NULL,
  `alamat` VARCHAR(300) NOT NULL,
  `tgl_lahir` DATE NOT NULL,
  `gol_darah` VARCHAR(2) NOT NULL,
  `agama` VARCHAR(45) NOT NULL,
  `status` VARCHAR(25) NOT NULL,
  `kartu_keluarga_id` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`nik`),
  INDEX `fk_penduduk_kartu_keluarga_idx` (`kartu_keluarga_id` ASC) VISIBLE,
  CONSTRAINT `fk_penduduk_kartu_keluarga`
    FOREIGN KEY (`kartu_keluarga_id`)
    REFERENCES `pwl2032`.`kartu_keluarga` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
